### ISSUE TITLE
SpatialNavigationVirtualizedList - Error: trying to assign focus to a non focusable node, js engine: hermes

### ISSUE THREAD

**Issue by goldqwert** [bamlab/react-tv-space-navigation#147] opened 2024-08-28 16:47 UTC
**Describe the bug**
When trying to set focus on a node in the `SpatialNavigationVirtualizedList` using the `focus()` method inside the `BackHandler` or similar event handlers, the app crashes with the following error: `Error: trying to assign focus to a non focusable node, js engine: hermes`
However, when focusing the same node using a button press (e.g., `<Button onPress={() => ref?.current?.focus(0)} />`), the focus works as expected without any errors, even when focusing on the first or last item in the list.

**To Reproduce**
_1. Set up a SpatialNavigationVirtualizedList with a ref to control focus.
2. Add a BackHandler event to trigger focus on the first node of the list.
3. Scroll down a few items or scroll to the end of the list.
4. Press the back button to trigger the focus on the first item in the list.
5. Observe the crash with the error message._

This error can be reproduced by adding `BackHandler` to the **GridWithLongNodesPage** in your example.

Here is a minimal reproducible code snippet:
```tsx
export const GridWithLongNodesPage = () => {
  const firstItemRef = useRef<SpatialNavigationNodeRef>(null);
  const lastItemRef = useRef<SpatialNavigationNodeRef>(null);
  const listRef = useRef<SpatialNavigationVirtualizedListRef>(null);

  useEffect(() => {
    const { remove } = BackHandler.addEventListener('hardwareBackPress', () => {
      listRef?.current.focus(0); // This will be crash the app if we scroll a few items or scroll to the end of the list
      return true;
    });
    return () => remove();
  }, []);

  return (
    <Page>
      <CenteringView>
        <GridContainer>
          <SpatialNavigationScrollView
            useCssScroll
            offsetFromStart={HEADER_SIZE + 20}
            ascendingArrow={<BottomArrow />}
            ascendingArrowContainerStyle={styles.bottomArrowContainer}
            descendingArrow={<TopArrow />}
            descendingArrowContainerStyle={styles.topArrowContainer}
          >
            <SpatialNavigationNode alignInGrid>
              <DefaultFocus>
                <>
                  <FirstRow ref={firstItemRef} />
                  <SecondRow ref={lastItemRef} />
                  <ButtonRow firstItemRef={firstItemRef} lastItemRef={lastItemRef} />
                </>
              </DefaultFocus>
            </SpatialNavigationNode>
            <Spacer gap="$6" />
            <ProgramListWithTitle title="Imperative focus on virtualized list" listRef={listRef} />
            <Row direction="horizontal">
              <Button
                label="Go to first"
                onSelect={() => {
                  listRef.current.focus(0);
                }}
              />
              <Button
                label="Go to last"
                onSelect={() => {
                  listRef.current.focus(999);
                }}
              />
            </Row>
            <Spacer gap="$20" />
          </SpatialNavigationScrollView>
        </GridContainer>
      </CenteringView>
    </Page>
  );
};
```

**Expected behavior**
The focus should be successfully set on the specified node (e.g., the first item in the list) when the focus() method is called inside the BackHandler or any other event handler, just as it does when called in a button's onPress event.

**Screenshots**
![Screenshot 2024-08-28 at 18 30 34](https://github.com/user-attachments/assets/c25a1f79-f3ba-4cbc-b583-a6b2e82b92f2)

**Version and OS**
 - Library version: 4.0.0
 - React Native version: from this lib packages/example/package.json "react-native": "npm:react-native-tvos@0.74.1-0"
 - OS [e.g. Android, web]: Android, IOS, on the web the list simply does not scroll to the beginning of the list and a log and error are visible in the browser console

**Additional context**
This issue appears to occur specifically when the focus is attempted in BackHandler. It seems related to the element not being ready or fully rendered at the time of the focus attempt. Adding delays `(e.g., setTimeout)` or using `InteractionManager.runAfterInteractions()` does not resolve the issue.

Any insights or potential workarounds would be greatly appreciated :) Thank you!

**Comment by pierpo** [comment] 2024-09-09 10:30
Hey! Sorry I missed your issue, I was on vacation 😱 

Thank you for the detailed message. That's extremely helpful, and we appreciate a lot 🙌 

If I understand correctly, we have a PR that we never merged that does implement the same thing as you: going back to the beginning of a virtualized list upon back press.
Can you have a look and test it? It was supposed to work properly (except on tvOS I think 😭)
https://github.com/bamlab/react-tv-space-navigation/pull/85

If it does work, can you compare implementations to understand what would be wrong? 😁 (if anything's wrong)

**Comment by pierpo** [comment] 2024-09-11 15:24
OK, I did reproduce the issue on the given PR. The imperative `focus(index)` method of the lists is buggy when used while another element is focused on the list.

We didn't catch it because the buttons `Go to first` and `Go to last` on the given page are pressed when the list is not focused.

I'll try to find a solution!

**Comment by pierpo** [comment] 2024-09-11 16:41
I have a fix that needs clean-up, but I did reproduce your issue and it seems to fix it 😊 
It needs further testing though, but I'll try to work on it tomorrow 😁

**Comment by pierpo** [comment] 2024-09-13 08:37
I merged the fix 🎉  It still needs to be published but it should solve your issue 😁

**Closed by pierpo** 2024-09-13 08:37 UTC
Labels: bug
