### ISSUE TITLE
onSelect only triggered when long press

### ISSUE THREAD

**Issue by huynhttdev** [bamlab/react-tv-space-navigation#44] opened 2023-12-19 09:46 UTC
**Describe the bug**
```
<SpatialNavigationNode onSelect={triggerAction}>

 </SpatialNavigationNode>
```

onSelect only triggered when long press. I need onSelect triggered one time i press

**Comment by pierpo** [comment] 2023-12-21 09:59
Hey!

Are you experiencing this on Android?
It's the second time someone mentions this issue https://github.com/bamlab/react-tv-space-navigation/issues/39#issuecomment-1853401950

And it feels like this is not related to the lib, more to the way we propagate down the event to the lib.

Could you confirm that?
You can add console logs to your remote control handler.

**Comment by pierpo** [comment] 2024-01-30 17:01
Can you also provide the device you're working with? Is it an emulator or an actual device?

**Comment by zay1x** [comment] 2024-02-01 03:33
I found solution for it, thanks for your support! @pierpo

**Comment by pierpo** [comment] 2024-02-01 09:04
Awesome! Can you share the solution? 😊

**Comment by manjunath-nuveb** [comment] 2024-02-07 06:48
Working for me after this fix 

https://github.com/kevinejohn/react-native-keyevent/issues/52#issuecomment-688061593

**Comment by manjunath-nuveb** [comment] 2024-02-07 08:55
Happening only when I open keyboard.

**Comment by rcasanova27** [comment] 2024-06-11 03:05
A mi me sucede igual, a lo mejor pueden compartir como lo solucionaron?

**Comment by pierpo** [comment] 2024-09-11 12:16
I'm closing this as the issue is not explicit enough. Feel free to reopen with a more illustrated example or a reproducible example.

**Closed by pierpo** 2024-09-11 12:16 UTC
Labels: bug, needs more details
